project_id = "sbtfhtllzpurjprivqoi"

[functions.api]
verify_jwt = false

[functions.send-proposta-email]
verify_jwt = false

[functions.upload-proposta-publica]
verify_jwt = false

[functions.harmony-crm]
verify_jwt = false

[functions.send-termo-aceite]
verify_jwt = true

[functions.processar-assinatura]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false

[functions.generate-contract-manual]
verify_jwt = false

[functions.emily-chat]
verify_jwt = false

[functions.aceitar-cotacao]
verify_jwt = false
