export * from './types';
export { HeroSection } from './HeroSection';
export { ComoFuncionaSection } from './ComoFuncionaSection';
export { DadosPessoaisForm } from './DadosPessoaisForm';
export { DadosVeiculoForm } from './DadosVeiculoForm';
export { ResultadoCotacao } from './ResultadoCotacao';
export { BeneficiosSection } from './BeneficiosSection';
export { ConfiancaSection } from './ConfiancaSection';
export { CTAFinalSection } from './CTAFinalSection';
export { PagamentoSection } from './PagamentoSection';
export { LandingFooter } from './LandingFooter';
export { CadastroContaForm } from './CadastroContaForm';
export { DocumentosUploadForm } from './DocumentosUploadForm';
export { LandingNavbar } from './LandingNavbar';
export { QuemSomosSection } from './QuemSomosSection';
export { ServicosSection } from './ServicosSection';
export { ArtigosSection } from './ArtigosSection';
export { ContatoSection } from './ContatoSection';
